postgresql: &postgresql
  adapter: postgresql
  host: localhost
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: cuanto_debemos_development

test:
  <<: *postgresql
  database: cuanto_debemos_test

production:
  <<: *postgresql
  database: cuanto_debemos_production
